fragment ParticipantFragment on ParticipantRecord {
	id
	title
	intro(markdown: false)
	image {
		...ImageFragment
	}
	year {
		...YearFragment
	}
	content {
		value
		blocks {
			__typename
			... on ImageRecord {
				__typename
				id
				layout
				image {
					...ImageFragment
				}
			}
			... on ImageGalleryRecord {
				__typename
				id
				images {
					...ImageFragment
				}
			}
			... on ButtonRecord {
				__typename
				id
				text
				url
			}
			... on VideoRecord {
				__typename
				id
				title
				video {
					height
					width
					title
					provider
					providerUid
					thumbnailUrl
					url
				}
			}
			... on RecordInterface {
				__typename
				id
			}
		}
	}
	slug
	_createdAt
}
