fragment ParticipantFragmentLight on ParticipantRecord {
	id
	name
	intro(markdown: false)
	image {
		...ImageThumbnailFragment
	}
	imageEn {
		...ImageFragment
	}
	year {
		...YearFragment
	}
	slug
	_createdAt
}
