fragment ProgramFragmentLight on ProgramRecord {
	__typename
	_modelApiKey
	id
	title
	startDate
	endDate
	intro(markdown: false)
	time
	image {
		...ImageThumbnailFragment
	}
	imageEn {
		...ImageThumbnailFragment
	}
	location {
		...LocationFragmentLight
	}
	programCategory {
		id
		title
	}
	programPlace {
		id
		title
	}
	year {
		...YearFragmentLight
	}
	slug
}
