fragment YearFragment on YearRecord {
	id
	title
	participantName
	slug
	color {
		hex
		red
		green
		red
	}
	backgroundColor {
		hex
		red
		green
		red
	}
	background {
		...ImageFragment
	}
	loadingImage {
		...ImageThumbnailFragment
	}
}
