query AllAbouts($first: IntType = 100, $skip: IntType = 0, $year: ItemId) {
	abouts: allAbouts(
		filter: { year: { eq: $year } }
		first: $first
		skip: $skip
		orderBy: [_createdAt_DESC]
	) {
		...AboutFragment
	}
	pagination: _allAboutsMeta {
		count
	}
}

query About($slug: String!) {
	about(filter: { slug: { eq: $slug } }) {
		...AboutFragment
	}
}

query AllAboutsMenu {
	abouts: allAbouts(first: 100) {
		title
		slug
	}
}
