query AllExhibitions($locale: SiteLocale) {
	exhibitions: allExhibitions(locale: $locale, first: 100) {
		...ExhibitionFragment
	}
	pagination: _allExhibitionsMeta(locale: $locale) {
		count
	}
}

query Exhibition($slug: String!, $locale: SiteLocale) {
	exhibition(filter: { slug: { eq: $slug } }, locale: $locale) {
		...ExhibitionFragment
	}
}
