query AllParticipants {
	participants: allParticipants(orderBy: name_ASC) {
		...ParticipantFragment
	}
	pagination: _allParticipantsMeta {
		count
	}
}

query Participant($slug: String!) {
	participant(filter: { slug: { eq: $slug } }) {
		...ParticipantFragment
	}
}
