query AllParticipants($locale: SiteLocale) {
	participants: allParticipants(locale: $locale, first: 100, orderBy: name_ASC) {
		...ParticipantFragment
	}
	pagination: _allParticipantsMeta(locale: $locale) {
		count
	}
}

query Participant($slug: String!, $locale: SiteLocale) {
	participant(filter: { slug: { eq: $slug } }, locale: $locale) {
		...ParticipantFragment
	}
}
