query AllPrograms($locale: SiteLocale) {
	programs: allPrograms(locale: $locale, orderBy: startDate_DESC, first: 100) {
		...ProgramFragment
	}
	pagination: _allProgramsMeta(locale: $locale) {
		count
	}
}

query Program($slug: String!, $locale: SiteLocale) {
	program(filter: { slug: { eq: $slug } }, locale: $locale) {
		...ProgramFragment
	}
}

query AllProgramCategories($locale: SiteLocale) {
	programCategories: allProgramCategories(locale: $locale, orderBy: title_DESC, first: 100) {
		id
		title
	}
}
