query AllYears($locale: SiteLocale, $year: String, $first: IntType = 100, $skip: IntType = 0) {
	allYears(
		filter: { title: { neq: $year } }
		locale: $locale
		first: $first
		skip: $skip
		orderBy: title_DESC
	) {
		...YearFragment
	}
	_allYearsMeta(locale: $locale, filter: { title: { neq: $year } }) {
		count
	}
}

query Year($title: String!, $locale: SiteLocale) {
	year(filter: { title: { eq: $title } }, locale: $locale) {
		...YearFragment
	}
}

fragment YearFragment on YearRecord {
	id
	title
	participantName
	introExhibitions(markdown: false)
	slug
	theme
	image {
		...ImageFragment
	}
	imageEn {
		...ImageFragment
	}
	color {
		hex
		red
		green
		red
	}
	backgroundColor {
		hex
		red
		green
		red
	}
	background {
		...ImageFragment
	}
	loadingImage {
		...ImageThumbnailFragment
	}
	fundedBy {
		id
		logo {
			...ImageMediumFragment
		}
		url
	}
	fullOpacity
}

fragment YearFragmentLight on YearRecord {
	id
	title
	participantName
	slug
	theme
	image {
		...ImageThumbnailFragment
	}
	color {
		hex
		red
		green
		red
	}
	backgroundColor {
		hex
		red
		green
		red
	}
}
